### ISSUE TITLE
Where does thread_local! come from?

### ISSUE THREAD

**Issue by cnrmck** [Deland-Labs/fungible-token-standard#61]
https://github.com/Deland-Labs/dfinity-fungible-token-standard/blob/10e6e12d57150d64ad00492561f5432f476a4f12/rust/dft_standard/src/state.rs#L4-L12

From which of these imports does `thread_local!` macro  come from?
```rust
use crate::token::*;
use dft_types::*;
use ic_cdk_macros::*;
```

**Comment by varik1770** [comment]
It's come from std.
refs: https://mmapped.blog/posts/01-effective-rust-canisters.html
